### ISSUE TITLE
Modify .txt search path to enable bash script to find bookmarks from any location

### ISSUE THREAD

**Issue by EdMorrell** [hamvocke/lnks#2]
This might just be me setting it up wrong, but I found that the bash script would only find your bookmarks.txt files when it was called from within the lnks directory. When I modified the following `cat *.txt` on the last line to: ` cat ~/lnks/*.txt` then this fixed the issue for me and I could run the command from any directory. I'm using a zsh terminal on a mac if that helps?

Aside from that, I love this tool and have already been getting loads of use out of it. Thanks for sharing.

**Comment by hamvocke** [comment]
Thanks for reporting! This is definitely not you setting up things wrong but a flaw in how the script reads in the `.txt` files.

I've addressed your issue in https://github.com/hamvocke/lnks/commit/e2c0b14bc8d6bdfc64b8c219782e85349fcf42b4. If you fetch the latest version of the `lnks.sh` script you should be all set.

Let me know if there are any other issues!
