### ISSUE TITLE
some options are broken now with new fzf version

### ISSUE THREAD

**Issue by nicolasmol** [hamvocke/lnks#7]
--border=rounded & --preview-window='up,1'
now are invalid

**Comment by hamvocke** [comment]
What makes you think that these two options are invalid now? What version of fzf are you using? And are you getting any error messages that would be helpful to figure out what's going on?

I just downloaded the latest fzf release (0.42.0) myself, and everything looks to be working fine. Both options are still listed in `fzf --help` still as well:

```
 --border[=STYLE]       Draw border around the finder
                            [rounded|sharp|bold|block|thinblock|double|horizontal|vertical|
                            top|bottom|left|right|none] (default: rounded)
```

```
--preview-window=OPT   Preview window layout (default: right:50%)
                           [up|down|left|right][,SIZE[%]]
                           [,[no]wrap][,[no]cycle][,[no]follow][,[no]hidden]
                           [,border-BORDER_OPT]
                           [,+SCROLL[OFFSETS][/DENOM]][,~HEADER_LINES]
                           [,default][,<SIZE_THRESHOLD(ALTERNATIVE_LAYOUT)]
```

**Comment by nicolasmol** [comment]
sorry sudo apt install fzf , installed 0.2..
Now fixed
